### ISSUE TITLE
[ISSUE] Issue with `databricks_metastore_data_access` resource. Error on destroy action

### ISSUE THREAD

**Issue by owlleg6** [databricks/terraform-provider-databricks#2829]
Hello, there is an issue with `databricks_metastore_data_access` on destroy
### Configuration
```hcl
# Copy-paste your Terraform configuration here
variable "databricks_account_id" {}
variable "storage_root" {}
variable "region" {}
variable "azure_access_connector_id" {}

provider "databricks" {
  alias      = "account"
  host       = "https://accounts.azuredatabricks.net"
  account_id = var.databricks_account_id
}

resource "databricks_metastore" "this" {
  name                                              = "primary"
  storage_root                                      = var.storage_root
  force_destroy                                     = true
  region                                            = var.region
}

resource "databricks_metastore_data_access" "this" {
  metastore_id  = databricks_metastore.this.id
  name          = "data-access"
  is_default    = true
  force_destroy = true

  # Azure Access Connector
  azure_managed_identity {
      access_connector_id = var.azure_access_connector_id
  }
}

```

### Actual Behavior

![image](https://github.com/databricks/terraform-provider-databricks/assets/3865349/b6fb007d-f83b-4ac3-aeec-8151562c0272)

![image](https://github.com/databricks/terraform-provider-databricks/assets/3865349/61ee890d-9eaa-4094-ac4e-2fd4fbb100eb)

### Steps to Reproduce

1. `terraform apply`
2. `terraform destroy`

### Terraform and provider versions
![image](https://github.com/databricks/terraform-provider-databricks/assets/3865349/f5e7393e-b778-4dc2-8b22-6ecead383dd4)

**Comment by alexott** [comment]
Can you try with release 1.28.1?

**Comment by owlleg6** [comment]
@alexott same issue. It's kinda weird, destroys always worked with previous provider versions.

**Comment by owlleg6** [comment]
same issue in gcp on destroy

**Comment by ethompsy** [comment]
Is there any known workaround?

I am stuck in this same issue, but it seems for me it has gone further that just the `destroy` phase. I get this on `apply` now:

```
│ Error: cannot create metastore data access: Storage Credential 'data-hub-uc-access' already exists
│ 
│   with module.unity_catalog.databricks_metastore_data_access.this,
│   on .terraform/modules/unity_catalog/main.tf line 31, in resource "databricks_metastore_data_access" "this":
│   31: resource "databricks_metastore_data_access" "this" {
```

However, if I attempt to import the existing resource I get this error:

```
│ Error: The provider returned a resource missing an identifier during ImportResourceState. This is generally a bug in the resource implementation for import. Resource import code should not call d.SetId("") or create an empty ResourceData. If the resource is missing, instead return an error. Please report this to the provider developers. 
```

So I cannot create, import, or destroy the `databricks_metastore_data_access` in much the same way as reported.

**Comment by tanmay-db** [comment]
Hi @ethompsy, can you check if using previous provider version unblocks this issue for the time being?

**Comment by mgyucht** [comment]
@ethompsy The underlying issue causing force-delete to fail has been fixed upstream. The fix is planned to be released in a maintenance release mid-next week. We'll update back here when it is released so you can try it out.

**Comment by himanshu-gsynergy** [comment]
Facing the same issue on latest version 1.30.0, but It worked after changing the version to 1.26.0.

**Comment by RamaDevi2000** [comment]
Hi team, 
customers were still facing issues on version 1.28.0.

**Comment by alexott** [comment]
closing as confirmed

**Comment by mattthaber** [comment]
This is still happening for me after upgrading to 1.30, i dont think this is "resolved" 

> cannot delete metastore data access: Storage credential 'XXXXXXX' cannot be deleted because it is configured as this metastore's root credential. Please update the metastore's root credential before attempting deletion.

**Comment by SrihasaAkepati** [comment]
@owlleg6 @alexott @mgyucht Issue still persists with provider version 1.30. JPMorgan Chase is encountering the issue and would like to have this as soon as possible. 

- Workaround to change the default storage credential worked but it is not a feasible solution as they have many metastores to work with. 
- They cannot downgrade the provider version as they have dependency with volumes which is compatible only with databricks Provider version of 1.30.0.

They would like to have the fix in 1.30 as early as possible. Please check.

**Comment by alexott** [comment]
Cc: @nkvuong

**Comment by nkvuong** [comment]
@SrihasaAkepati @mattthaber could you confirm that you have set `force_destroy = true` for the `databricks_metastore_data_access` resource?

I just tested this morning
```  # databricks_metastore_data_access.test will be destroyed
  - resource "databricks_metastore_data_access" "test" {
      - force_destroy = true -> null
      - id            = "***" -> null
      - is_default    = true -> null
      - metastore_id  = "***" -> null
      - name          = "sa-east-1" -> null
      - owner         = "***" -> null
      - read_only     = false -> null

      - aws_iam_role {
          - role_arn = "***" -> null
        }
    }

Plan: 0 to add, 0 to change, 2 to destroy.
databricks_metastore_data_access.test: Destroying... [id=***]
databricks_metastore_data_access.test: Destruction complete after 1s
databricks_metastore.test: Destroying... [id=***]
databricks_metastore.test: Destruction complete after 0s

Destroy complete! Resources: 2 destroyed.
```

**Comment by SrihasaAkepati** [comment]
@nkvuong My bad, it worked with force_destroy. Thanks for quick help.
