### ISSUE TITLE
[ISSUE] Issue with `databricks_mws_credentials` resource

### ISSUE THREAD

**Issue by crankswagon** [databricks/terraform-provider-databricks#3016]
`databricks_mws_credentials` using account level provider configured with username + password auth failing in new version.

```
Error: cannot read mws credentials: invalid Databricks Account configuration
  
  with databricks_mws_credentials.this[0]
  on databricks-workspace.tf line 1, in resource "databricks_mws_credentials" "this":
    1: resource "databricks_mws_credential" "this {

```

### Configuration

```hcl
resource "databricks_mws_credentials" "this" {
  count           = var.environment == "redacted" ? 1 : 0
  provider        = databricks.account
  account_id      = local.databricks_account_id
  role_arn        = aws_iam_role.cross_account_role.arn
  credential_name = "${local.prefix}-creds"
  depends_on      = [aws_iam_role_policy.this]
}


provider "databricks" {
  alias    = "account"
  host     = "https://accounts.cloud.databricks.com"
  username = var.databricks_account_username
  password = var.databricks_account_password

}


```

### Expected Behavior
Applies as per normal

### Actual Behavior
Failed with invalid account error when using provider version `1.31.1`

### Steps to Reproduce

`terraform plan`

### Terraform and provider versions

Works with `1.31.0` 
Fails with `1.31.1`

### Is it a regression?
Yes; last worked with `1.31.0`

### Debug Output
Possibly due to Go SDK refactor in new version

**Comment by VPAI-Bixal** [comment]
Commenting that we are seeing this issue as well.  Works on `1.31.0` breaks on `1.31.1`.

**Comment by forma-wolf** [comment]
Whose the team responsible for testing versions of provider. This is affecting us too.

**Comment by jpoletto-imo** [comment]
This is effecting us too

**Comment by burck1** [comment]
We are seeing this problem too. We rolled back to `v1.31.0` for the time being.

**Comment by mgyucht** [comment]
This is addressed in https://github.com/databricks/terraform-provider-databricks/pull/3028. We plan to release the provider with this fix by EOD tomorrow. I will close this issue as there is no work to be done, and you can update to the release with this fix (will be 1.32.0) once it is available.

**Comment by donatasm** [comment]
Bumped to version `1.32.0`, still getting exactly same error, as in version `1.31.1`.

**Comment by donatasm** [comment]
Additionally, same error if optional `account_id` is removed from `databricks_mws_credentials` as mentioned in https://github.com/databricks/terraform-provider-databricks/pull/3028#pullrequestreview-1781557910.

**Comment by BKY3-forpeople** [comment]
We are still seeing the issue on 1.33.0

**Comment by donatasm** [comment]
I was able to update successfully to `1.33.0` after these changes:
* optional `account_id` is removed from all `databricks_mws_credentials` resources
* `account_id` is set in provider:
```
provider "databricks" {
  alias      = "mws"
  host       = "https://accounts.cloud.databricks.com"
  account_id = var.databricks_account_id
  // ...
}
```

**Comment by VPAI-Bixal** [comment]
> I was able to update successfully to `1.33.0` after these changes:
> 
>     * optional `account_id` is removed from all `databricks_mws_credentials` resources
> 
>     * `account_id` is set in provider:
> 
> 
> ```
> provider "databricks" {
>   alias      = "mws"
>   host       = "https://accounts.cloud.databricks.com"
>   account_id = var.databricks_account_id
>   // ...
> }
> ```

Tried this on `1.33.0` still having the `invalid Databricks Account configuration` error.

**Comment by VPAI-Bixal** [comment]
> I was able to update successfully to `1.33.0` after these changes:
> 
>     * optional `account_id` is removed from all `databricks_mws_credentials` resources
> 
>     * `account_id` is set in provider:
> 
> 
> ```
> provider "databricks" {
>   alias      = "mws"
>   host       = "https://accounts.cloud.databricks.com"
>   account_id = var.databricks_account_id
>   // ...
> }
> ```

So far this seems to be working for us, thanks!
