### ISSUE TITLE
[ISSUE] Issue with `databricks_cluster` resource

### ISSUE THREAD

**Issue by videnden** [databricks/terraform-provider-databricks#3599]
### Configuration
Hello,

Since last week when we updated our cluster configuration we are receiving errors when execute terraform apply.

data "databricks_node_type" "smallest" {
  local_disk = true
}

data "databricks_spark_version" "latest_lts" {
  long_term_support = true
}

resource "databricks_cluster" "shared_autoscaling" {
  cluster_name            = var.dev_cluster
  spark_version           = data.databricks_spark_version.latest_lts.id
  node_type_id            = data.databricks_node_type.smallest.id
  autotermination_minutes = 15
  autoscale {
    min_workers = 1
    max_workers = 5
  }
  cluster_log_conf {
    s3 {
      destination = "s3://example/${var.dev_cluster}"
      region      = "eu-west-1"
    }
  }
}

### Expected Behavior
configuration to be updated.

### Actual Behavior
Terraform apply fails with the following error:

Error: cannot update cluster: The specified IOPS, 0, is not in the range 3,000 - 16,000

### Steps to Reproduce

1. `terraform apply`

### Terraform and provider versions
terraform {
  required_version = ">=1.6.5"
  required_providers {
    databricks = {
      source  = "databricks/databricks"
      version = ">=1.44.0"
    }
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

### Is it a regression?
Yes

**Comment by edwardfeng-db** [comment]
Thanks for raising! I think the [PR](https://github.com/databricks/terraform-provider-databricks/pull/3601) linked here should fix this issue. But it doesn't really systematically solve this class of issue, we should have a systematic solution after we fully migrate to the new plugin framework.

**Comment by privard** [comment]
Same issue here. Creating a new cluster with 1.45.0 still sets `ebs_volume_iops` and `ebs_volume_throughput` to 0 in the state by default, with schema_version: 4. Any subsequent changes to the cluster fail with either "Error: cannot update cluster: The specified IOPS, 0, is not in the range 3,000 - 16,000" or "Error: cannot update cluster: The specified throughput, 0, is not in the range 125 - 1,000"

**Comment by edwardfeng-db** [comment]
Thanks for raising @videnden @privard. Is it easy for you guys to try out this solution I'm proposing here? https://github.com/databricks/terraform-provider-databricks/pull/3613

**Comment by videnden** [comment]
I tried to change the provider version to the new one "1.45.0" and also added the suggested changes
`aws_attributes {
   availability     = "SPOT_WITH_FALLBACK"
   ebs_volume_count = null
   ebs_volume_size  = null
   ebs_volume_type  = null
}`
But we are still receiving the same issue and we can't downgrade to previous version.

**Comment by edwardfeng-db** [comment]
@videnden @casstait-vgw Thanks for raising!

I've merged https://github.com/databricks/terraform-provider-databricks/pull/3613 and you can see I added a new test case. I could reproduce it without the change in this PR and have verified that this fixed the issue.

There will be a new release of the provider this week, please let me know if there's still problem after the release. Thanks!

**Comment by videnden** [comment]
I've just tested it and can confirm that the issue **still persist.** I am trying to change the cluster log configuration and still receiving the same IOPS related issue.
I've tried again with and without adding the above mentioned aws attributes.

**Comment by edwardfeng-db** [comment]
@videnden I tried modifying the cluster log configuration in my own testing environment and it is working with the new change I've merged. Can you share the exact config and config changes you are using?

**Comment by videnden** [comment]
Hi @edwardfeng-db ,

Below is the cluster configuration we have.

`resource "databricks_cluster" "development_dbricks_cluster" {
  count                   = local.include_in_dev_and_intg
  cluster_name            = var.dev_cluster
  data_security_mode      = "USER_ISOLATION"
  runtime_engine          = "PHOTON"
  provider                = databricks.workspace
  spark_version           = "13.3.x-scala2.12"
  node_type_id            = "m5d.xlarge"
  autotermination_minutes = 20
  init_scripts {
    volumes {
      destination = "/Volumes/...../${var.cluster_init_script}"
    }
  }
  spark_env_vars = {
    PYSPARK_PYTHON = "/databricks/python3/bin/python3"
  }
  spark_conf = {
    "spark.metrics.namespace"                            = "${var.dev_cluster}-${terraform.workspace}"
    "spark.hadoop.javax.jdo.option.ConnectionUserName"   = "admin"
    "spark.hadoop.javax.jdo.option.ConnectionURL"        = "jdbc:derby:memory:myInMemDB;create=true"
    "spark.hadoop.javax.jdo.option.ConnectionDriverName" = "org.apache.derby.jdbc.EmbeddedDriver"
  }
  cluster_log_conf {
    s3 {
      destination = "s3://example-bucket/${var.dev_cluster}"
      region      = "eu-west-1"
    }
  }
  aws_attributes {
    instance_profile_arn = databricks_instance_profile.dbricks_instance_profile_s3_access.id
  }
  autoscale {
    min_workers = "2"
    max_workers = "8"
  }
  depends_on = [databricks_catalog.dtpl_configuration_catalog]
}`

I am trying to change the cluster_log_conf part of the code to:
`  cluster_log_conf {
    s3 {
      destination = "s3://example-bucket/${var.something_else}"
      region      = "eu-west-1"
    }
  }`
  
  and receiving the same error "Error: cannot update cluster: The specified IOPS, 0, is not in the range 3,000 - 16,000"
  
 When you test the solution are you using the same old cluster created with provider 1.44.0 were the issue exist? Should we recreate all our clusters in order the changes you did to be properly reflected in the resources in the state?

**Comment by edwardfeng-db** [comment]
@videnden Thanks! Can you also share the debug logs?

**Comment by videnden** [comment]
Hello @edwardfeng-db,

Here is the debug log attached 
[15_Terraform debug.txt.zip](https://github.com/databricks/terraform-provider-databricks/files/15480742/15_Terraform.debug.txt.zip)

**Comment by videnden** [comment]
Hi @edwardfeng-db, it now works.
Thank you
